var cardCollection = [
	{name: "Fruititude",
		rating: 4.5,
		taste: 4.5,
		ambiance: 4,
		customerService: 5,
		distance: 0},
	{name: "Tapioca Express",
		rating: 2,
		taste: 2,
		ambiance: 3,
		customerService: 4,
		distance: 0},
	{name: "M.I.Tea Express",
		rating: 4,
		taste: 4,
		ambiance: 3,
		customerService: 4,
		distance: 0},
	{name: "Tea N More",
		rating: 3.5,
		taste: 3,
		ambiance: 5,
		customerService: 3.5,
		distance: 0},
	{name: "Boba Bar &amp; Desserts",
		rating: 4.5,
		taste: 4,
		ambiance: 4,
		customerService: 4,
		distance: 0},
	{name: "It&#39;s Boba Time",
		rating: 3.5,
		taste: 3.5,
		ambiance: 5,
		customerService: 4,
		distance: 0},
	{name: "Tea Station",
		rating: 4,
		taste: 4,
		ambiance: 3.5,
		customerService: 3,
		distance: 0},
	{name: "Infinitea",
		rating: 4.5,
		taste: 4.5,
		ambiance: 5,
		customerService: 4,
		distance: 0},
	{name: "Trinitea",
		rating: 4.5,
		taste: 5,
		ambiance: 4,
		customerService: 5,
		distance: 0},
	{name: "Lollicup",
		rating: 4,
		taste: 3.5,
		ambiance: 4,
		customerService: 2,
		distance: 0},
	{name: "Up2You",
		rating: 4.5,
		taste: 3.5,
		ambiance: 3.5,
		customerService: 4.5,
		distance: 0},
	{name: "Tap Tap Boba",
		rating: 4.5,
		taste: 4.5,
		ambiance: 4.5,
		customerService: 4,
		distance: 0}
];